### ISSUE TITLE
Ensure correct handling of escaped semicolons in multi valued attributes

### ISSUE THREAD

**Issue by smangelsdorf** [ausaccessfed/shib-rack#11]
From @bradleybeddoes:

>  Per https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAttributeAccess
> 
> ```
> Within each CGI variable or header (see below), multiple attribute values are separated 
> by a semicolon, and semicolons in values are escaped with a backslash. The data should 
> be interpreted as UTF-8, which is a superset of ASCII.
> ```
> 
> Thus `somelong\;value;another long value` would currently be incorrectly parsed. It should fall out as `['somelong;value', 'another long value']`.

**Comment by bradleybeddoes** [comment]
Solved by #12
